In [ ]:
# ドライブのマウント
from google.colab import drive
drive.mount('/content/drive')

# 適宜自分のApplicationPATHまで変更
APP_PATH = '/content/drive/Othercomputers/LAPTOP-3BHDM0TI/windows_research/workspace/research/carbon-steel-classification'

# 2.1 前準備

import numpy as np
import matplotlib.pyplot as plt
import torch
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import TensorDataset, DataLoader
from torch import nn
import torch.nn.functional as F
from torch import optim

import cv2
from PIL import Image

Mounted at /content/drive


In [ ]:
# 2.2 訓練データとテストデータの用意

# CIFAR10データセットの読み込み
# train_dataset = torchvision.datasets.CIFAR10(root='./data/Normalize/',
#                                              train=True,
#                                              download=True,
#                                              transform=transforms.Compose([
#                                                  transforms.ToTensor(),
#                                                  transforms.Normalize(
#                                                      [0.5, 0.5, 0.5],
#                                                      [0.5, 0.5, 0.5],
#                                                  )
#                                              ]))

# test_dataset = torchvision.datasets.CIFAR10(root='./data/Normalize/',
#                                             train=False,
#                                             download=True,
#                                             transform=transforms.Compose([
#                                                 transforms.ToTensor(),
#                                                 transforms.Normalize(
#                                                     [0.5, 0.5, 0.5],
#                                                     [0.5, 0.5, 0.5],
#                                                 )
#                                             ]))

transform = transforms.Compose([transforms.ToTensor()])
trainset = torchvision.datasets.CIFAR10(root='./data/unprocessed/', train=True, download=True)


# train_datasetの中身を確認
print("trainset size: {}".format(type(trainset)))
# print("train_dataset size: {}".format(train_dataset.size()))    # 画像サイズ
print("train_dataset size: {}".format(trainset))

image, label = trainset[0]
print("image size: {}".format(type(image)))
# print("image ndim: {}".format(image.ndim))
# print("train_dataset size: {}".format(train_dataset[].size()))    # 画像サイズ
# print("image size: {}".format(image.size()))    # 画像サイズ
print("label: {}".format(label))                # ラベルサイズ
print("image")
print(image)

100%|██████████| 170498071/170498071 [00:06<00:00, 25589283.10it/s]


Extracting ./data/Normalize/cifar-10-python.tar.gz to ./data/Normalize/
Files already downloaded and verified
trainset size: <class 'torchvision.datasets.cifar.CIFAR10'>
train_dataset size: Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data/unprocessed/
    Split: Train
image size: <class 'PIL.Image.Image'>
label: 6
image
<PIL.Image.Image image mode=RGB size=32x32 at 0x7F7346941690>


In [ ]:
# 作成データセットの確認

datasets_npz_x1 = np.load(APP_PATH + '/dataset_npz/x.1_dataset/sc_x10_960_x1.npz')

CATEGORIES=["S10C","S15C","S25C","S35C","S45C","S55C"]

x = datasets_npz_x1['x']
y = datasets_npz_x1['y']

image = x[0]
print("before image type: {}".format(type(image)))
print("image size: {}".format(image.size))
print("image len: {}".format(len(image)))
print("image ndim: {}".format(image.ndim))
print("image shape: {}".format(image.shape))
print("image dtype: {}".format(image.dtype))

print("image[0] size: {}".format(image[0].size))

print("label: {}".format(y[0]))
print("image")
print(image)

# 3チャンネルに変換
image = Image.fromarray(image)
print("image dtype: {}".format(type(image)))
image = image.convert("RGB")
print("image mode: {}".format(image.mode))
image = np.asarray(image, np.uint8) # むりやり3チャンネルにしているので表記上はRGBだが実際はL
print("image shape: {}".format(image.shape))
image = np.transpose(image, (2, 0, 1))
print("image transpose shape: {}".format(image.shape))


before image type: <class 'numpy.ndarray'>
image size: 921600
image len: 960
image ndim: 2
image shape: (960, 960)
image dtype: uint8
image[0] size: 960
label: 5
image
[[ 65  54  47 ... 117 119 115]
 [ 74  62  53 ... 110 115 107]
 [ 74  88 112 ... 115 113 111]
 ...
 [ 80  79  89 ...  90  98 134]
 [ 84  82 100 ... 239 240 235]
 [ 85  84 103 ... 238 236 236]]
image dtype: <class 'PIL.Image.Image'>
image mode: RGB
image shape: (960, 960, 3)
image transpose shape: (3, 960, 960)


In [ ]:
# ダウンロードデータの確認

# train_datasetの中身を確認
print("trainset type: {}".format(type(trainset)))
print("trainset shape: {}".format(trainset.shape))


image, label = trainset[0]
print("before image type: {}".format(type(image)))
image = np.array(image)
print("after image type: {}".format(type(image)))

print("image size: {}".format(image.size))
print("image len: {}".format(len(image)))
print("image ndim: {}".format(image.ndim))
print("image shape: {}".format(image.shape))
# print("image[0] size: {}".format(image[0].size))
print("label: {}".format(label))
print("image")
print(image)
print("image ch")
print(image[2])





trainset type: <class 'torchvision.datasets.cifar.CIFAR10'>


AttributeError: ignored

In [ ]:
# データ操作の練習

lists = []
for i in range(5):
    a_np = np.array([[i, i+1, i+2],
                     [i+3, i+4, i+5]])
    lists.append(a_np)


numpy_array = np.array(lists)
print(numpy_array)



matrix = np.empty(shape=1, dtype=float)
matrix = np.ones((2, 2, 2, 2))

print(matrix)
print('=======================')
new_matrix = np.ones((2, 2, 2))
new_matrix_2 = np.ones((2, 2, 2))


a = np.arange(1)
print(a)

matrix = np.ones((2))
new_matrix = np.append(new_matrix, new_matrix, axis=0)

a_2d = np.arange(9).reshape(3, 3)

a_3d = np.arange(3).reshape(1, 3)
print(a_3d)
print('=======================')





a = np.append(a, a_2d, axis=0)
print(a)
print('=======================')


# print(a)
# print('=======================')

a = np.append(a, new_matrix_2, axis=0)
print(a)
print('=======================')


[[[0 1 2]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]

 [[3 4 5]
  [6 7 8]]

 [[4 5 6]
  [7 8 9]]]
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]
[0]
[[0 1 2]]


ValueError: ignored